-- Pull AFPNP orders
SELECT
    lpad(P.ALIAS, 10, '0') as EMPI,
    P_MRN.ALIAS as HUP_MRN,
    ORDERS.ORDER_ID,
    CA.ACCESSION,
    ORDER_ALIAS.ALIAS ORDER_ALIAS_number,
    RESULT.TASK_ASSAY_CD,
    CV_order.DISPLAY DTA,
    PERFORM_RESULT.PERFORM_RESULT_ID,
    CV_RS.DISPLAY RESULT_STATUS,
    PERFORM_RESULT.ASCII_TEXT,
    PERFORM_RESULT.RESULT_VALUE_NUMERIC,
    PERFORM_RESULT.RESULT_VALUE_ALPHA,
    PERFORM_RESULT.RESULT_VALUE_DT_TM,
    PERFORM_RESULT.LESS_GREAT_FLAG,
    PERFORM_RESULT.PERFORM_DT_TM,  -- NOTE: tz needs to be adjusted
    PERFORM_RESULT.UPDT_DT_TM RESULT_UPDT_DT_TM,  -- NOTE: tz needs to be adjusted
    CV_SR.DISPLAY SERVICE_RESOURCE,
    PERFORM_RESULT.PARENT_PERFORM_RESULT_ID,
    RESULT_EVENT.EVENT_DT_TM,  -- NOTE: tz needs to be adjusted
    RESULT_EVENT.EVENT_TYPE_CD,
    C.DRAWN_DT_TM as DRAWN_DT_TM,  -- NOTE: tz needs to be adjusted
    C.received_dt_tm as RECEIVED_DT_TM  -- NOTE: tz needs to be adjusted
FROM RESULT
  join ORDERS
    ON ORDERS.ORDER_ID = RESULT.ORDER_ID
  join ORDER_ALIAS
    ON ORDER_ALIAS.ORDER_ID = ORDERS.ORDER_ID
  join PERSON_ALIAS P
    ON P.PERSON_ID = ORDERS.PERSON_ID
  join PERSON_ALIAS P_MRN
    ON P_MRN.PERSON_ID = ORDERS.PERSON_ID
  join PERFORM_RESULT
      ON PERFORM_RESULT.RESULT_ID = RESULT.RESULT_ID
  join CONTAINER_ACCESSION CA
      ON CA.CONTAINER_ID = PERFORM_RESULT.CONTAINER_ID
  join CODE_VALUE CV_order
    ON CV_order.CODE_VALUE = RESULT.TASK_ASSAY_CD
  join CODE_VALUE CV_SR
      ON CV_SR.CODE_VALUE = PERFORM_RESULT.SERVICE_RESOURCE_CD
  join CODE_VALUE CV_RS
      ON CV_RS.CODE_VALUE = PERFORM_RESULT.RESULT_STATUS_CD
  join CONTAINER C
      ON CA.CONTAINER_ID = C.CONTAINER_ID
  join V500.RESULT_EVENT
      ON RESULT_EVENT.PERFORM_RESULT_ID = PERFORM_RESULT.PERFORM_RESULT_ID
WHERE
  ORDERS.ORDER_MNEMONIC = 'AFP'
  AND ORDERS.ACTIVE_IND = 1
  AND P.ACTIVE_IND = 1
      AND P.ALIAS_POOL_CD = 4483934 -- CMRN 4488530 --HUP MRN
  AND P_MRN.ACTIVE_IND = 1
      AND P_MRN.ALIAS_POOL_CD = 4488530 --HUP MRN
  AND PERFORM_RESULT.PERFORM_DT_TM >=  to_date('01-JAN-2020','DD-MON-YYYY')
  AND ORDER_ALIAS.ACTIVE_IND = 1
  AND ORDER_ALIAS.END_EFFECTIVE_DT_TM > SYSDATE
  AND RESULT_EVENT.EVENT_TYPE_CD IN (1738, 1723) -- NOT 1733 -- performed
;